### PR TITLE
Update pytest-qt to 2.1.0

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by jakirkham** [comment]
Please remember to fork and propose PRs from branches on your fork in the future @nicoddemus . Note that all branches on the feedstock automatically deploy once they pass.

**Comment by nicoddemus** [comment]
@jakirkham sorry I just noticed that I pushed to the feedstock directly instead to my fork. Really sorry about that!

Should I cancel the builds and re-open the PR?

**Comment by jakirkham** [comment]
No worries. Have done the same myself before. Feel free to let it run out and merge as it is a simple change and some packages may have already deployed.

**Comment by nicoddemus** [comment]
OK, thanks! 👍

**Comment by jakirkham** [comment]
TBH this is fairly frequent phenomenon and everyone has done this at least once. We should really have some improvements to mitigate this issue. Here are some we have discussed. Feel free to raise other suggestions and/or provide feedback on any of them.
- A mechanism to require PRs from one's fork. ( https://github.com/conda-forge/conda-forge-webservices/issues/75 )
- Explicit statement of deployment branch. ( https://github.com/conda-forge/conda-forge.github.io/issues/87 )
- Clearer, more apparent documentation?

**Comment by nicoddemus** [comment]
Thanks @jakirkham!

I will re-render the conda-smithy recipe because we got the "input line too long on linux" issue.

**Comment by nicoddemus** [comment]
Superseded by #5

**Pull request closed without merging**
